# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{irxml}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Mongeau"]
  s.date = %q{2010-03-10}
  s.description = %q{Gem for handling IRXML's API}
  s.email = %q{matt@toastyapps.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "irxml.gemspec",
     "lib/irxml.rb",
     "lib/irxml/edgar.rb",
     "lib/irxml/stock.rb",
     "lib/runner.rb",
     "test/fixtures/edgar.xml",
     "test/fixtures/historic_stock_quote.xml",
     "test/fixtures/stock_quote.xml",
     "test/helper.rb",
     "test/test_irxml_edgar_document.rb",
     "test/test_irxml_edgar_list.rb",
     "test/test_irxml_stock_historic_quote.rb",
     "test/test_irxml_stock_quote.rb"
  ]
  s.homepage = %q{http://github.com/toastyapps/irxml}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gem for handling IRXML's API}
  s.test_files = [
    "test/helper.rb",
     "test/test_irxml_edgar_document.rb",
     "test/test_irxml_edgar_list.rb",
     "test/test_irxml_stock_historic_quote.rb",
     "test/test_irxml_stock_quote.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

